
'use client';

import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Users, Mail, Briefcase, BarChart3 } from 'lucide-react';

const mockAnalyticsData = [
  { name: 'Computer Science', generated: 0 },
  { name: 'Graphic Design', generated: 0 },
  { name: 'Biology', generated: 0 },
  { name: 'Marketing', generated: 0 },
  { name: 'Engineering', generated: 0 },
];

export function AnalyticsDashboard() {
  const [totalGenerated, setTotalGenerated] = useState(0);
  const [emailsSent, setEmailsSent] = useState(0);
  const [uniqueFields, setUniqueFields] = useState(0);
  const [chartData, setChartData] = useState(mockAnalyticsData);

  useEffect(() => {
    // Simulate fetching data
    setTotalGenerated(Math.floor(Math.random() * 1000) + 200);
    setEmailsSent(Math.floor(Math.random() * 300) + 50);
    setUniqueFields(Math.floor(Math.random() * 50) + 10);
    
    setChartData(prevData => prevData.map(item => ({
      ...item,
      generated: Math.floor(Math.random() * 150) + 10,
    })));
  }, []);

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-semibold flex items-center">
        <BarChart3 className="mr-2 h-6 w-6 text-primary" />
        Analytics Overview
      </h2>
      <div className="grid gap-6 md:grid-cols-3">
        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Paths Generated</CardTitle>
            <Briefcase className="h-5 w-5 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalGenerated.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">+10.2% from last month (mock)</p>
          </CardContent>
        </Card>
        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Emails Sent</CardTitle>
            <Mail className="h-5 w-5 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{emailsSent.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">+5.1% from last month (mock)</p>
          </CardContent>
        </Card>
        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Unique Fields of Study</CardTitle>
            <Users className="h-5 w-5 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{uniqueFields.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">Trending: Comp Sci (mock)</p>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle>Career Paths Generated by Field (Mock Data)</CardTitle>
        </CardHeader>
        <CardContent className="h-[350px]">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip
                contentStyle={{
                  backgroundColor: 'hsl(var(--background))',
                  borderColor: 'hsl(var(--border))',
                }}
              />
              <Legend />
              <Bar dataKey="generated" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>
      <Card className="bg-yellow-50 border-yellow-200 shadow-md">
        <CardHeader>
            <CardTitle className="text-yellow-700 text-sm">Developer Note</CardTitle>
        </CardHeader>
        <CardContent className="text-yellow-600 text-sm">
            The analytics data displayed here is randomly generated for demonstration purposes.
            For real analytics, you would need to integrate a database and data collection mechanisms.
        </CardContent>
      </Card>
    </div>
  );
}
